name: pencil
description: Pencil is a modern Minecraft launcher.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.8.1
  bitsdojo_window: ^0.1.5
  desktop_webview_window:
    git:
      url: https://github.com/Dreta/desktop-webview-window.git
      ref: f2c7fff
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 6c66ad2
  url_launcher: ^6.1.12
  dynamic_color: ^1.6.6
  http: ^0.13.6
  transparent_image: ^2.0.1
  provider: ^6.0.5
  path: ^1.8.3
  file_picker: ^5.2.10
  uuid: ^3.0.7
  crypto: ^3.0.3
  archive: ^3.3.7
  contextmenu: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/profiles/

  fonts:
    - family: Product Sans
      fonts:
        - asset: fonts/ProductSans-Regular.ttf
        - asset: fonts/ProductSans-Italic.ttf
          style: italic
        - asset: fonts/ProductSans-Bold.ttf
          weight: 700
        - asset: fonts/ProductSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/ProductSans-Light.ttf
          weight: 300
        - asset: fonts/ProductSans-LightItalic.ttf
          weight: 300
          style: italic
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
